- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfextensions/endpoint/EndpointConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfextensions/endpoint/EndpointLookup.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseConfig.groovy
- broker/src/main/resources/application.yml
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/cfextensions/endpoint/EndpointLookupSpec.groovy
result of discussion on https://github.com/swisscom/open-service-broker/pull/4
now using native yaml features instead of parsing ip ranges and protocols in the code.
> refactor ip range and protocols to allow for multiple ranges/protocols

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BindingController.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/dto/automation/AuthenticationDto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/dto/automation/ProcessDto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/opsmanager/OpsManagerFacade.groovy
- broker/src/main/resources/application.yml
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/OpsManagerFacadeSpec.groovy
This updates the automation config to be compatible with Ops Manager version 3.4.
Changes:
- New fields added: proceses.featureCompatibilityVersion, auth.keyfileWindows
- ensures required field AuthMechamnism is present when removing processes / replicasets from a group
- fixes bug which returned 'void' instead of a valid http response on unbind requests.
> Update automation config to be compatible with MongoDB Ops Manager version 3.4

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/KubernetesRedisFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/config/AbstractKubernetesServiceConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/AbstractKubernetesFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/KubernetesFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/KubernetesFacadeRedis.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/config/KubernetesRedisConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/service/KubernetesRedisServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/service/state/KubernetesServiceProvisionState.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/AbstractKubernetesFacadeSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/KubernetesFacadeRedisSpec.groovy
- broker/src/test/resources/kubernetes/kubernetes-podlist-response-notready.json
- broker/src/test/resources/kubernetes/kubernetes-podlist-response-ready.json
**Motivation**
After requesting service deployment to kubernetes and getting an ACCEPTED response, OSB should check if the deployment is actually successful before responding with the provision state SUCCESS.
**Description**
This checks pods with our custom label healthz set to true or optionally all pods within the namespace, whether they are in state ready.
Whether only pods with label healthz should be considered for checking readiness can be configured with config `enablePodLabelHealthzFilter`.
> add check whether kubernetes service deployment is successful

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/AbstractKubernetesFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/KubernetesFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/KubernetesFacadeRedis.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/service/KubernetesRedisServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/service/state/KubernetesServiceDeprovisionState.groovy
**Motivation**
When a k8s service instance gets deleted we want to make sure the deletion actually worked. Furthermore deleting service instances which do not exist in the first place, should work without any errors.
**Description**
As we are deleting service instances by deleting namespaces, we simply check if getting the namespace returns a 404 status code. For that step there's the new state `CHECK_NAMESPACE_DELETION_SUCCESSFUL`.
> make sure k8s namespace is deleted

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/FirstAsyncProvisioningStepFailsFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/ProvisioningPersistenceService.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/ProvisioningService.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/test/DummyFailingServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/test/DummyServiceProvider.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/provisioning/ProvisioningServiceSpec.groovy
**Motivation**
While testing kubernetes services, we experienced issues with some API calls. These led to deployment failures, which could not be resolved by requesting the service instance deletion, as OSB had not saved the service instance in the database. For async services this is done after the first step, which already partly failed.
**Description**
With this change, the service instance gets saved whether it will succeed or not.
> All service instance provision requests are saved

- broker/src/main/resources/application.yml
This PR sets the port of MongoDB OpsManager to the default port
> set proper default port for opsmanager

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/KubernetesFacadeRedis.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/KubernetesFacadeRedisSpec.groovy
Writing to injected objects is not thread safe.
This fix makes a copy of the injected map and pushes the remaining maps to the copy.
> fix race condition in Kubernetes Redis provision

- broker/build.gradle
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfextensions/extensions/ExtensionProvider.groovy
Instead of using the free external provider https://mermade.org.uk we'll use the swagger-parser 2.0.0-rc3 parser. This library provides an easy to use conversion from 2.0 to 3.0.
Also make it possible to filter by tags.
> use OpenAPIV3Parser to return OpenAPI 3.0 definition

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/binding/ServiceBindingPersistenceService.groovy
*Why support changing service bindings*
Certain custom actions are based on service bindings. As these allow to change details and credentials, the bindings have to be updateable.
> Support changing Service Bindings

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/BindingParametersFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/ServiceInstanceBindingDtoConverter.groovy
Since we save the credentials string with like this
`"credentials": {
"foo": "bar"
}`
The fetch return for a service_bindings looks like this:
`"credentials": "\"credentials\": {\n\"foo\": \"bar\"\n}"`
This nesting of credentials does not make sense, with this change credentials looks like this:
`"credentials": "{\"foo\": \"bar\"}"`
Furthermore parameters are now also returned in the service_binding fetch.
> return parameters and avoid nesting credentials in json

- broker/build.gradle
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/StringGenerator.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/util/StringGeneratorSpec.groovy
This is useful to be compliant to certain systems with silly password requirements like Oracle [ora12c_strong_verify_function](https://docs.oracle.com/database/121/DBSEG/authentication.htm#GUID-1168CD4D-659E-432D-9CB7-F5733129657D).
> make it possible to define rules for random string generation

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BaseController.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BindingController.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/error/ErrorCode.groovy
**Problem**
Currently open-service-broker responds with a 404 when requesting a deprovision or unbinding and the binding or instance can not be found. For platforms relying on the [Open Service Broker API specification](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md) this leads to an error as it should return a 410 in this case, and the instance or binding can not be deleted.
**Proposal**
As specified by the openservicebrokerapi, return 410 HTTP status code when unbinding/deprovisioning a service binding/instance and the object is not found.
> return 410 for non existing service instances and binding

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacadeFactory.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/common/TemplateConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/templates/KubernetesTemplateManager.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacadeFactorySpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacadeSpec.groovy
**Motivation**
We want to be able to use the application.yml as the single source of truth for open-service-broker configuration.
**Problem**
bosh-templates have to be configured as separate files.
**Proposal**
Use the same structure we already use for kubernetes services and add the configuration to the application.yml.
> support configuring bosh-templates in application.yml

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/AsyncServiceFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/AuthenticationFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/BindingParametersFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BindingController.groovy
**Problem**
Our status codes are not always correct when fetching, deprovisioning or unbinding and the resource does not exist. This can be problematic if the client relies on correct status codes.
**Proposal**
Make sure return codes are as specified in the [Open Service Broker API specifications](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md).
> Fix status codes for unbinding, deprovision and fetch not existing

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/RestTemplateBuilder.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/util/LoggingRequestInterceptorSpec.groovy
Make addLoggingRequestInterceptor method in RestTemplateBuilder synchronized, to circumvent the thread unsafe use of the interceptors list.
This should address the issue mentioned in #104
> Synchronize addLoggingRequestInterceptor

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/opsmanager/OpsManagerFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/statemachine/MongoDbEnterpriseProvisionState.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProviderSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/OpsManagerFacadeSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/statemachine/MongoDbEnterpriseProvisionStateSpec.groovy
This PR adds the update service functionality for MongoDB Enterprise.
It adds a new parameter 'featureCompatibilityVersion' which defines the feature compatibility version of MongoDB which was introduced with MongoDB 3.4.
> Update service for MongoDB Ent

- broker/build.gradle
- broker/src/main/resources/application-info.yml
- broker/src/main/resources/application.yml
`/version` endpoint returned `${version}` because application.yml was not expanded, due to some templates we are using, which should not be expanded.
The new application-info.yml can be extended with more custom information, given it is within the `info:` object.
Also update flyway and springboot dependencies on PATCH level.
> Return actual OSB version for /version endpoint

- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/bosh/client/BoshRestClientTest.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/client/BoshRestClient.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/HttpHelper.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/client/BoshRestClientSpec.groovy
First call to BOSH API invokes a check for authentication method. If authentication method is `uaa` a token will be fetched and stored. Further calls will use the saved token unless it's expired.
> Support BOSH uaa authentication

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/BaseFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbServiceProvider.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBServiceProviderSpec.groovy
For easier reuse of the RelationalDb the functionality is being moved to a facade class.
> Move RelationalDb functionality into a facade class

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/model/ProvisionRequest.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/model/RequestWithParameters.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/model/UpdateRequest.groovy
This PR introduces a new interfaced that can be used during provisioning and updating a service instance. It is meant as a replacement for explicit usage of ProvisionRequest and UpdateRequest. Instead the new RequestWithParameters should be used.
This replacement should enable reuse of provision states during update service.
> Improvement: common base model for requests

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/AbstractKubernetesFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/KubernetesFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/service/state/KubernetesServiceProvisionState.groovy
this PR removes generic Kubernetes update state in favor of service specific states
> remove generic Kubernetes update state

- CHANGELOG.md
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/ServiceUpdateFunctionalSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/util/ServiceLifeCycler.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/UpdatingController.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/model/ProvisionRequest.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/model/RequestWithParameters.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/AbstractKubernetesFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/KubernetesFacadeRedis.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/updating/UpdatingPersistenceService.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/updating/UpdatingService.groovy
- broker/src/main/resources/db/migration/V1_0_22__add_service_context_to_updateRequest.sql
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/controller/UpdatingControllerSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/AbstractKubernetesFacadeSpec.groovy
This feature adds a context object to the update request as it is present in the provision request.
This allows for context specific actions during update and it allows reuse of provision code sequences
> Add platform context to UpdateRequest

- broker/build.gradle
As described here https://github.com/spring-projects/spring-boot/issues/9242 build with bootJar can not be used as a dependency as we're doing it right now. For the way we're using the broker builds, I'd prefer to keep the smaller 1.4 MB jar instead of the big 80 MB bootJar.
> Build a simple jar instead of a bootJar

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshTemplate.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshTemplateSpec.groovy
**Problem**
When using more advanced features while deploying with bosh potential quotes can come in the way. Simple example, when trying to use variables:
Template:
```
mysql_admin_password: "{{mysql-admin-password}}"
```
Expected Result:
```
mysql_admin_password: ((mysql-admin-password))
```
This would replace with the "bosh variable" mysql-admin-password.
Actual Result:
```
mysql_admin_password: "((mysql-admin-password))"
```
This will not work as it will simply be interpreted as a string.
**Proposal**
Always get rid of quotes (if any) when replacing with values, this should be no problem as by default values are interpreted as strings.
> Remove unnecessary quotes in bosh-manifest

- .circleci/config.yml
- circleci-publish.sh
- scripts/bump_and_create_release.sh
- scripts/circleci-publish.sh
- travis-publish.sh
Every night at 1:00 CircleCI will start the `build_and_release_nigthly` workflow, which will, based on the content in `CHANGELOG.md` in the develop branch, bump the version and release to master.
**How to use it:**
So you can set the following in the `CHANGELOG.md` to trigger a new release:
line starting with `- [MAJOR]` to bump a major release
line starting with `- [MINOR]` to bump a minor release
any other content will bump a patch release
As long as the there is no content in the `Unreleased` section, there will be no action taken.
**Example CHANGELOG.md:**
```
[Unreleased]
- [MAJOR] This will trigger the script to bump a major version, e.g. 2.4.2 to 3.0.0
- [MINOR] In absence of MAJOR this will bump a minor version, e.g. 2.4.2 to 2.5.0
- In absence of MAJOR or MINOR this will bump a …
```
> Automate release process

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBShieldTarget.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBShieldTargetSpec.groovy
Shield does not ignore null values and will therefore fail if null values are not omitted.
> omit null values for MariaDBShieldTarget

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/statemachine/MongoDbEnterpriseDeprovisionState.groovy
When the group on the opsmanager is removed the deprovisioning and unbinding does not work anymore. That makes rather time-consuming to cleanup.
> ignore 404 during unbind and deprovision of MongoDBEnterprise

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/Audit.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/util/AuditSpec.groovy
Logs messages can then be extracted via GREP/REGEX to forward redirect to a audit location.
> Add Static Audit class with specific format

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/backup/job/AbstractBackupJob.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/backup/job/AbstractBackupRestoreJob.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/backup/job/RestoreJob.groovy
The job id for backup and restore jobs is not the service instance guid. With this fix, the correct log context is being set with MDC.
> set the serviceinstanceguid as log context

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/LogContextEnrichInterceptor.groovy
Ensure all LogContextEnrichInterceptor exceptions are caught, as this should not interfere with operations.
> Catch LogContextEnrichIntercpetor exceptions

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbServiceProvider.groovy
- broker/src/main/resources/application.yml
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBServiceProviderSpec.groovy
MariaDB ServiceProvider now supports dashboardUrl in provision response if `dashboardPath` per cluster is not empty.
> Add dashboardUrl for RelationalDbServiceProvider

- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/util/RestTemplateBuilderTest.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/test/httpserver/HttpServerConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/RestTemplateBuilder.groovy
This commit adds authorization via Bearer token for the
RestTemplateBuilder. The additional method will add an "Authorization"
HTTP header to any request via interceptors.
> Add Bearer Authorization for RestTemplateBuilder

- CHANGELOG.md
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/dto/automation/ReplicaSetDto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/opsmanager/OpsManagerFacade.groovy
In order to use mongodb version 4.0.x, protocolVersion must be set in the automation config.
> insert protocolVersion in automationConfig for mongodb 4.0.x

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/ParentServiceFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/ProvisioningController.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/error/ErrorCode.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/ProvisioningService.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/ParentServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/test/ParentDummyServiceProvider.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/provisioning/ProvisioningServiceSpec.groovy
**Problem:**
Services provided in a parent / child relationship have to bring their own logic to manage the given restrictions. This leads to a lot of duplicated code, as the problems are bound to be very similar.
**Proposal:**
The trait ParentServiceProvider will provide the default logic, which is automatically applied when the ServiceProvider `implements ParentServiceProvider`. The default logic can be overridden by every ServiceProvider.
**Limitations:**
In the plan for the parent serviceprovider the parameter `max_children` has to be set (default is unlimited).
> ParentServiceProvider to handle parent service providers

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/AsyncServiceProvider.groovy
this allows service providers to trigger actions or do validations before the the 'provision' is scheduled to be executed.
> Add overridable functions before async actions in AsyncServiceProvider.

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshBasedServiceConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshTemplateCustomizer.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/statemachine/BoshDeprovisionState.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/statemachine/BoshProvisionState.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/statemachine/BoshStateMachineFactory.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProvider.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacadeSpec.groovy
- broker/src/test/resources/bosh/cloud_config_template_mongodbent_v5.yml
Generic configs for bosh based services will be handled similar to the deployment template. To use any generic configs, simply define in the service config. Example:
```
com.swisscom.cloud.sb.broker.service.mongodbent:
boshConfigs:
- templateName: <name of template in serviceTemplates>
type: <config type, e.g. cloud>
```
If none are set, there will also no generic config be set.
**Breaking change**
With this change services that implement `BoshTemplateCustomizer` have to implement the method following method, regardless if they are using generic configs:
`void customizeBoshConfigTemplate(BoshTemplate template, String type, ProvisionRequest provisionRequest)`
> handle generic configs for bosh based services in statemachine

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/GenericConfig.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacadeSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/bosh/DummyBoshBasedServiceConfig.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/bosh/DummyBoshBasedServiceConfigTest.groovy
- broker/src/integration-test/resources/application-test.yml
Spring configuration properties need setters, which are only generated by Groovy when no access modifier is present.
> fix: remove access modifier for GenericConfig properties

- .circleci/config.yml
Correcting the circle-ci workflow to launch builds that publish the tags
done in develop
> fix: Make the tags done in develop launch publish

- broker/build.gradle
- broker/core/build.gradle
- build.gradle
- gradle.properties
I added the configuration we are using internally for publishing other
projects. I had to include some new project properties at gradle
properties for correct maven pom generation and take out the generation
of test artifacts at the broker core because nebula.test-jar plugin is
the one that is introducing this kind of hack (we should not depend in
test jars)
> fix: Correct nebula publishing configuration

- .circleci/config.yml
The idea is a sequential workflow, we can't publish and tag in parallel.
> chore: Make publishing be done after tagging

- .circleci/config.yml
It looks that System.getenv('BINTRAY_USER') of our publishing.gradle is
not working in circleci environment (maybe because is a docker container
with different env?). Now we are passing directly to gradle publish
those credentials already stored in circle-ci.
> chore: Pass bintray credentials as env variables

- README.md
It is a fast way of showing which is the last version build and
published.
> docs: Include bintray last version badges

- gradle/dependencies.gradle
We were having two different versions (1.0.4 and 1.1.1) of
micrometer-registry-influx which was causing a classpath problem.
> fix: Align micrometer-registry-influx to v1.1.1

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubServiceImpl.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubServiceProvider.groovy
- broker/core/src/main/resources/application.yml
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/CredHubBindingParametersFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/CredHubServiceProviderFunctionalSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubIntegrationSpec.groovy
If you are using `spring.credhub` property path, Spring tries to
configure credhub beans. And if enable=false, first it configures beans
that are NOT going to be used and that probably are not correctly
configured.
Changing the name of the watched property in the @OnProperty makes all
the problems go away.
> fix: Rename 'spring.credhub.enable` to osb.c.e

- gradle/publishing.gradle
fix parameter name `bintrayPassword` to `bintrayApiKey`
> chore: fix Gradle publishing for OSB developer README

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacade.groovy
Using BoshFacade with @Component is problematic, as multiple service
configs can implement BoshBasedServiceConfig and a resolution like
@Primary would need to be defined (which makes not much sense).
Furthermore BoshFacade can be instantiated with static create method,
when needed.
> bugfix: Do not use BoshFacade as component

- README.md
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/ServiceDefinitionController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/servicedefinition/ServiceDefinitionProcessor.groovy
Due to the behaviour of the [ServiceDefinitionInitializer](https://github.com/swisscom/open-service-broker/blob/develop/broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/servicedefinition/ServiceDefinitionInitializer.groovy#L77) the API
endpoints for service-definition must be deprecated, as any changes done
at runtime will be disabled or deleted on a restart.
> Deprecate service-definition API

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/statemachine/StateMachineBasedServiceProvider.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/statemachine/DummyAsyncServiceConfig.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/statemachine/DummyStateMachineBasedServiceProvider.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/statemachine/StateMachineBasedServiceProviderTest.groovy
Due to the inheritance used with StatemachineBasedServiceProvider and
the changes made to [AsyncServiceProvider](https://github.com/swisscom/open-service-broker/blob/develop/broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/AsyncServiceProvider.groovy#L51), a corresponding constructor needs to be defined.
> bug: StateMachineBasedServiceProvider constructor missing

- .circleci/config.yml
On CircleCI we get the error `Could not get lock /var/lib/apt/lists/lock` for an unknown reason. The fix implemented here has been proposed in the discussion [here](https://discuss.circleci.com/t/could-not-get-lock-var-lib-apt-lists-lock/28337).
> chore: lock /var/lib/apt/lists

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/UpdatingController.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/ServiceUpdateFunctionalSpec.groovy
For synchronous service update success only status codes 200 and 202 are accepted. Currently we are returning 201 which the platform has to interpret as failure, [see spec](https://github.com/openservicebrokerapi/servicebroker/blob/v2.13/spec.md#response-3).
> bug: wrong update status code

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/opsmanager/OpsManagerFacade.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProviderSpec.groovy
Since OpsManagerFacade is using @Retryable for the method
`checkAndRetryForOnGoingChanges()` it has to be injected by Spring to
`MongoDbEnterpriseServiceProvider`, so that the annotation is interpreted.
> bug: inject OpsManagerFacade for @Retryable

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/dto/access/OpsManagerUserDto.groovy
- broker/src/main/resources/application-broker.yml
This PR updates the OpsManager DTO with the recently added DATA_ACCESS roles.
Additionally it adds the role 'GROUP_DATA_ACCESS_READ_ONLY' to the default configured roles.
> Add new OpsManager roles to DTO

- README.md
For proper tagging we decided to use merging rather than rebasing. Unfortunately some PRs were rebased rather than merged. We now forbid rebasing in GitHub repository configuration and release the missed PRs with this PR.
> chore: properly merge for correct tagging

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/CFServiceDtoConverter.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/PlanDtoConverter.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/PlanDtoConverterSpec.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/dto/CFPlanDto.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/dto/CFServiceDto.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/servicedefinition/dto/PlanDto.groovy
`ServiceDto` and `CFServiceDto` both have the field `plans` which is
problematic, because `ServiceDto` extends `CFServiceDto`. Furthermore
`PlanDto` classname is duplicated whereby `PlanDto` extends from `PlanDto`
> fix: remove duplicate plans name

- broker/core/bosh-service/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshTemplate.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshTemplateSpec.groovy
The now deprecated replace method of BoshTemplate was calling two times
to string replaceAll method. With replaceAllNamed we are just calling
once.
With the added replaceAll we could pass the regular expression to be used.
> bug: Improve the BOSH variables replacement

- broker/core/bosh-service/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacade.groovy
The bosh template customizer could return an Immutable collection that
makes this method fail.
> bug: Return a copy of customized service details

- .circleci/config.yml
Functional tests are taking around half an hour and we were launching
them when merging the  branch and when releasing the tag. Starting from
now, just launching them when releasing the tag: when merging the branch
they are not launched. That way, developers can update their develop
branch with the merged change and use a SNAPSHOT dependecy locally while
circle-ci is building the release.
> chore: Only launch functional tests before release

- broker/core/src/main/resources/application.yml
The config in application.yml should be as small as possible, to reduce
the risk of having test config in production systems. Therefore removing
credhub config which is not a default for production.
> chore: remove unnecessary credhub config

- broker/core/database/src/main/groovy/com/swisscom/cloud/sb/broker/repository/PlanRepository.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/model/ServiceInstance.groovy
In a multithreaded environment we won't have access to the initial
session context that loaded this entity from database. So I added a
method for eager fetching the plan with its parameters and I modififed
the ServiceInstance relationship with Plan to be eager fetched
(otherwise metric calculation will fail in a different thread).
> fix: Set eager fetch type for plans

- broker/core/database/src/main/groovy/com/swisscom/cloud/sb/broker/repository/ServiceInstanceRepository.groovy
We need to know the number of children in certain steps and places that
are not sharing same hibernate session, so with this method we can fetch
them eagerly.
> feat: Add method for fetch eagerly children of instance

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubServiceProviderConfiguration.groovy
We need ClientOptions for 'getBrokerDefault' Spring bean, and that bean
is conditional on property 'spring.credhub.url'
> fix: Add spring property so ClientOptions is loaded

- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/util/ServiceDetailHelperSpec.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/model/ServiceInstance.groovy
When we want to delete a ServiceInstance we want to delete its details
also. And when we want to create a ServiceInstance we want to store its
ServiceDetails. So the correct cascade should be ALL.
> fix: Add Cascade.ALL to ServiceDetails of ServiceInstance

- .circleci/config.yml
Otherwise we are not able to check fast which test is failing in
circle-ci.
> chore: Store test results for all stages of build

- broker/core/bosh-service/src/main/java/com/swisscom/cloud/sb/broker/services/bosh/client/BoshDirectorTask.java
- broker/core/database/src/main/groovy/com/swisscom/cloud/sb/broker/repository/ServiceBindingRepository.groovy
- broker/core/database/src/main/groovy/com/swisscom/cloud/sb/broker/repository/ServiceInstanceRepository.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/model/LastOperation.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/model/ServiceBinding.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/model/ServiceInstance.groovy
In the case of the relationship of instances with bindings, we will need
to fetch the bindings of an instance when we are in different threads,
so included the left join. I have also changed fro List to Set because
otherwise Hibernate can't fetch two collections eagerly (we should use
Set instead of List always, but I can't change List<Details> because
there are dependencies to the List interface in other classes :-()
In the case of bindings I eagerly get the to-one relationships, cascade
all the details (because they don't make sense without being associated
to a binding) and added method for eagerly fetching Details (which we
need for sure when accessing from different threads).
> fix: Rationalize relationships for bindings and instances

- model/src/main/groovy/com/swisscom/cloud/sb/broker/model/ServiceInstance.groovy
The @NotBlank is incorrectly behaving in combination with the hibernate
validators: Error creating bean with name 'serviceDefinitionInitializer': Invocation of init method failed; nested exception is javax.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint 'javax.validation.constraints.NotBlank' validating type 'java.lang.String'. Check configuration for 'guid'
> fix: remove not blank check for service instance

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/BackupRestoreProvider.groovy
The may be many reasons for a backup to be missing
an externalId. We should allow the deletion of those
backups.
> bug: Allow deleting backups with missing externalId

- broker/core/metrics/src/main/groovy/com/swisscom/cloud/sb/broker/metrics/MetricsConfiguration.groovy
As there are multiple Beans found matching the metrics services
within the configuration, the "real" implementations should be
preferred over the "NoOp" implementations.
> refactor: Set preferred metric beans

- broker/core/database/src/main/groovy/com/swisscom/cloud/sb/broker/context/ServiceContextPersistenceService.groovy
- broker/core/database/src/main/resources/db/migration/V1_0_26__update_disallow_null_value_in_service_context.sql
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/context/ServiceContextHelperSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/AsyncServiceFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/ServiceContextFunctionalSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/KubernetesFacadeRedisSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBServiceProviderSpec.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/model/ServiceContextDetail.groovy
`value` and `key` should not allow any null values
as this leads to problems later on (e.g. running
`hashCode()` throws a `NullPointerException`) and it
makes no sense to have a null value for those fields.
> bug: Disallow null values for ServiceContextDetail

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubServiceProviderConfiguration.groovy
Resolving of the correct serviceProvider is done by a hard coded pattern, this was not
correct for credHubServiceProvider with this configuration.
> fix: incorrect bean name for credHubServiceProvider.

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubServiceProviderConfiguration.groovy
Using `@Value("test")` will set the literal value "test"
and not the configuration property "test".
> bug: Load CredHub config from properties

- README.md
- broker/core/configuration/src/main/groovy/com/swisscom/cloud/sb/broker/services/credential/CredentialStoreConfiguration.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/AdminController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/ServiceInstanceCleanup.groovy
- broker/core/src/main/java/com/swisscom/cloud/sb/broker/cfextensions/ServiceInstancePurgeInformation.java
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/AdminControllerSpec.groovy
- broker/src/functional-test/resources/application-test.yml
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBConfig.groovy
When purging a service instance, some helpful
information about the purge should be returned.
In practice `ServiceInstance` has been shown to
be unusable due to the huge amount of data.
> feat: Information for service instance purge

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/statemachine/MongoDbEnterpriseDeprovisionState.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/statemachine/MongoDbEnterpriseProvisionState.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/statemachine/MongoDbEnterpriseDeprovisionStateSpec.groovy
Retrieve the service detail as an optional and handle missing values accordingly. in the deprovision case, we will accept it, as we want to roll back and should support deprovisions of incomplete provisions. for provision it should fail with a correct error.
> fix: switch to optional implementation

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/BackupRestoreProvider.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/BackupService.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/shield/BackupDeregisterInformation.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/shield/ShieldClient.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/shield/ShieldRestClient.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/shield/ShieldRestClientV1.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/ServiceInstanceCleanup.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/util/test/DummySynchronousBackupCapableServiceProvider.groovy
- broker/core/src/main/java/com/swisscom/cloud/sb/broker/cfextensions/ServiceInstancePurgeInformation.java
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/backup/shield/ShieldClientTest.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/AdminControllerSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/backup/shield/ShieldBackupRestoreProviderSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/provisioning/DummySystemBackupServiceProvider.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/provisioning/ServiceInstanceCleanupSpec.groovy
When a customer uses the backup feature a job and target
are created in the shield system. With this change all
service instance associated backup resources are removed
> refactor: Deregister user and system driven backup

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/AsyncServiceFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/BindingParametersFunctionalSpec.groovy
Not Retrievable response code was switched to FORBIDDEN.
The corresponding functional tests were not adapted to this
change.
> bug: Set Correct Expected Status Code In Test

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BaseController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/ProvisioningController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/UpdatingController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/updating/UpdatingService.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/util/SensitiveParameterProvider.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/util/SensitiveParameterProvider.java
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/controller/ProvisioningControllerSpec.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/util/SensitiveParameterProviderSpec.groovy
Logging sensitive parameters as null can be misleading
as you cannot know whether any or which parameters are set.
With this change all top-level parameter keys are shown.
> bug: Log Sensitive Parameters As Confidential

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/updating/UpdatingService.groovy
The update request is due to the lazy db removed from the update request table,
preventing any statemachine to access the values. This is not feasible.
> bug: sensitive provider does delete update request.

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/updating/UpdatingPersistenceService.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/updating/UpdatingService.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/DummyAsyncServiceConfig.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/DummyAsyncServiceProvider.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/updating/UpdatingServiceSpec.groovy
In the case of synchronous services updating a service
can be persisted as it is now in the UpdatingService.
For asynchronous services however it's problematic to
update the service instance on request, as it might fail
at a later stage and the service instance entry is then
in a wrong state.
> bug: Update Should Be Persisted After Success

- broker/core/bosh-service/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacade.groovy
When the task response contains the state "error"
the task should be evaluated as failed.
> bug: Fail Bosh Task On Error

- README.md
- broker/core/build.gradle
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/AlertingClient.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/CleanupAction.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/CleanupConfiguration.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/CleanupController.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/CleanupInfoService.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/CleanupService.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/CleanupServiceConfiguration.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/OpsGenieAlertingClient.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/OpsGenieAlertingClientConfiguration.java
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cleanup/ScheduleConfiguration.groovy
- broker/core/src/main/java/com/swisscom/cloud/sb/broker/cleanup/Failure.java
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/cleanup/CleanupServiceSpec.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/cleanup/LongRunningAction.java
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/cleanup/OpsGenieAlertingClientSpec.groovy
Cleanup services can be used scheduled or manually triggered to have service instances cleaned up.
The cleanup services is designed to only support a single service type and not multiple.
> wip: feature: add cleanup service logic.

- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/util/RestTemplateBuilderSpec.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/util/RestTemplateBuilder.groovy
Using RestTemplateBuilder `withBearerAuthentication` or
`withBasicAuthentication`  can lead to `ConcurrentModificationException`
due to the modification of the interceptors. Using
`@Synchronized` resolves this issue.
> bug: RestTemplateBuilder With Auth Thread Unsafe

- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/util/RestTemplateBuilderTest.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/test/httpserver/HttpServerApp.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/util/RestTemplateBuilder.groovy
By allowing to set the httpclient retryhandler
cases like connection issues with PUT requests
can be retried, when the API is idempotent.
> refactor: Allow Setting RetryHandler
