swisscom/open-service-broker

- README.md
Changed server/src/main/resources/application.yml to broker/src/main/resources/application.yml
> Fixed configuration file path in README.txt

- README.md
Updated readme with eden v0.6.0 env vars.
> Latest eden has new env vars

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/CloudFoundryContextRestrictedAsyncServiceFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/test/CloudFoundryContextRestrictedDummyServiceProvider.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/KubernetesFacadeRedisSpec.groovy
added tests for checking that ServiceProvider is of CloudFoundryRestrictedOnly
> Add Functional Test for CloudFoundryRestrictedOnly Marker Interface

- broker/src/main/resources/db/migration/V1_0_11__create_table_service_context.sql
- broker/src/main/resources/db/migration/V1_0_14__fix_duplicate_service_context_migration.sql
Remove duplicate service_context records and delete orphan records
> Fix SQL Migration V1_0_11__create_table_service_context

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/ServiceInstanceDtoConverter.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/model/ServiceInstance.groovy
- To list childs of service instance, reference to parentReference
- Return only guid of parentReference in ServiceInstanceResponse
> fix child mapping and parentReference response

- README.md
- openshift-deploy.sh
A script to deploy osb on Openshift
> openshift deployment script

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/binding/FetchServiceBindingProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/binding/ServiceInstanceBindingResponseDto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/ServiceInstanceBindingDtoConverter.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BindingController.groovy
**Problem**
For certain service providers the fetch service binding need to be enriched with more information.
**Proposal**
With the FetchServiceBindingProvider interface service providers can have their own implementation for fetching the service binding.
> allow serviceproviders to customize fetch service binding

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/dto/BindRequestDto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/dto/ProvisioningDto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/dto/UpdateDto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BaseController.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/error/ErrorCode.groovy
Proposal for #79 
- respond with bad request status code when encountering validation errors with a request body
- return found issues in the error description
> respond with bad request status code on validation error

- client/src/main/groovy/com/swisscom/cloud/sb/client/ServiceBrokerClientExtended.groovy
The JSON Validation was added on the Endpoint but not on the client.
> #101: Add Json ContentType on create serviceDefinition

- broker/build.gradle
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/test/httpserver/HttpServerApp.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/ServiceBroker.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfextensions/extensions/ExtensionProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/templates/constants/AbstractTemplateConstants.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/servicedetail/AbstractServiceDetailKey.groovy
- broker/src/main/resources/application.yml
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacadeSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseBindResponseDtoSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/util/DtoValidationHelperSpec.groovy
- gradle/wrapper/gradle-wrapper.properties
This pull request is part of step 1 of the issue #111.
> Update outdated dependencies

- CHANGELOG.md
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/statemachine/StateMachineBasedServiceProvider.groovy
fixes #116 but may lead to breaking changes to serviceproviders using this provider.
> #116: Add LastOperationJobContext as parameter and change visibility

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/dto/automation/ProcessArgumentsV26Dto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/opsmanager/OpsManagerFacade.groovy
expose AuditLog for MongoDB Enterprise in automation config and enable it by default
> expose AuditLog for MongoDB Enterprise

- CHANGELOG.md
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/statemachine/StateMachineBasedServiceProvider.groovy
> #123: Add CompileStatic to class and fix Method calls

- CHANGELOG.md
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/util/test/DummySynchronousExtendedUsageServiceProvider.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/model/usage/extended/ServiceUsageItem.groovy
> #125: Change type of value in ServiceUsageItem

- CHANGELOG.md
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/BackupRestoreHelper.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/MariaDBAsynchronousFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/MariaDBBackupRestoreFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/MariaDBFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/MariaDBUsageFunctionalSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBClientSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbClientSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBClient.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBClientFactory.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBConnectionConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBShieldTarget.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbBindResponseDto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbClient.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbClientFactory.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbConfig.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbServiceProvider.groovy
- broker/src/main/resources/application.yml
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBServiceProviderSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBShieldTargetSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbBindResponseDtoSpec.groovy
Implementation of a MariaDB Service Provider that can manage multiple MariaDB Clusters.
> #11: Implement MariaDB Service Provider

- .circleci/config.yml
- README.md
- circleci-publish.sh
Address problem mentioned in #141 by moving from Travis to CircleCI.
> Move testing and building to CircleCI

- broker/build.gradle
> #163: Update SPOC dependency from RC to final release.

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/cfextensions/endpoint/EndpointService.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/CFExtensionsController.groovy
> Get correct endpointconfig

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/CredHubMigrationFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubMigrationInitializer.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubServiceImpl.groovy
> #170: Replace merge with save for database query

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubService.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/credhub/CredHubServiceImpl.groovy
Writes a certificate to CredHub
> Add writeCertificate feature to CredHubService

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/dto/Metadata.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/dto/Spec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/AbstractKubernetesFacade.groovy
> Pull service port information and resend this information to K8S on service update

- broker/src/main/resources/db/migration/V1_0_24__change_service_details_value_to_text.sql
> #103: Change _value column on service_detail to text.

- CHANGELOG.md
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/backup/shield/restClient/ShieldRestClientImpl.groovy
Fixes bug where shield backups could not be deleted due to a 404 returned by shield
> Fixes bug where shield backups could not be deleted

- broker/src/test/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/ErrorDtoConverterSpec.groovy
In Exception the message field contains the error message which we want to display in the lastOperation description.
> Change description field to message.

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/ExtensionProviderFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/controller/CFExtensionsController.groovy
- broker/src/main/resources/db/migration/V1_0_25__update_update_request_parameters_field_to_text.sql
- client/src/main/groovy/com/swisscom/cloud/sb/client/IServiceBrokerClient.groovy
- client/src/main/groovy/com/swisscom/cloud/sb/client/IServiceBrokerClientExtended.groovy
- client/src/main/groovy/com/swisscom/cloud/sb/client/ServiceBrokerClient.groovy
- client/src/main/groovy/com/swisscom/cloud/sb/client/ServiceBrokerClientExtended.groovy
This makes it a lot easier to make calls to custom endpoints with the 'common' client. All requests are authenticated.
> Update client to expose exchange function

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/servicedefinition/ServiceDefinitionProcessor.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/PlanDtoConverterSpec.groovy
This fixes an issue, where meta data are returned as map instead of list.
> Cast LinkedHashMap to Array.

- broker/build.gradle
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/MongoDbEnterpriseFunctionalSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProviderTest.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/ServiceBroker.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDBAutomationConfigUpdateNotCompletedException.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/dto/automation/BackupConfigDto.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/opsmanager/OpsManagerFacade.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/opsmanager/OpsManagerOngoingChangesChecker.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/statemachine/MongoDbEnterpriseDeprovisionState.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseServiceProviderSpec.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/statemachine/MongoDbEnterpriseDeprovisionStateSpec.groovy
Adds some additional checks for ongoing OpsManager deployments before and after binding calls.
> Feature reliable mongodbent bindings

- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacade.groovy
- broker/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacadeSpec.groovy
Make generic config management accessible through BoshFacade
> feat: add generic config management to BoshFacade

- .circleci/config.yml
- build.gradle
- gradle/publishing.gradle
They included some improvewments in the plugin.
> fix: Update to nebula-bintray version 7.2.7

- .circleci/config.yml
We were doing that before starting with the new release process.
> chore: De-encrypt the key ring correctly

- gradle.properties
- gradle/publishing.gradle
It looks that if the pom has any property generated dynamically from
certain gradle property should be in an afterEvaluate block:
https://docs.gradle.org/current/userguide/publishing_maven.html#publishing_maven:deferred_configuration
> chore: Fix maven pom generation

- model/src/main/groovy/com/swisscom/cloud/sb/broker/model/ServiceDetail.groovy
For making logs and exceptions make sense.
> bug: Add a string representation to ServiceDetail

- broker/core/bosh-service/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/BoshFacade.groovy
Details can have repeated keys (like 'host'), so not always is going to
be a Map. Adding another method in the API solves the problem.
> fix: Add API for getting task state from any collection

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbClient.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/relationaldb/RelationalDbServiceProvider.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/MariaDBUsageFunctionalSpec.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/kubernetes/facade/redis/service/KubernetesRedisServiceProvider.groovy
- broker/src/main/groovy/com/swisscom/cloud/sb/broker/services/mariadb/MariaDBClient.groovy
We are using slf4j with logback-classic implementation. Period.
> fix: Eliminate references to @Log4j

- broker/core/bosh-service/src/main/java/com/swisscom/cloud/sb/broker/services/bosh/client/BoshDeployment.java
- broker/core/bosh-service/src/main/java/com/swisscom/cloud/sb/broker/services/bosh/client/BoshDeploymentRequest.java
- broker/core/bosh-service/src/main/java/com/swisscom/cloud/sb/broker/services/bosh/impl/WebClientBoshDirectorService.java
- broker/core/database/src/main/groovy/com/swisscom/cloud/sb/broker/repository/ServiceInstanceRepository.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/CFExtensionsController.groovy
We will need them when there is not available a Hibernate Session, so
I'm adding it to the previously eagerly fetching method.
> fix: Get eagerly also details of ServiceInstance

- broker/core/bosh-service/src/main/java/com/swisscom/cloud/sb/broker/services/bosh/client/BoshWebClient.java
When BOSH server is returning a 4XX when trying to delete
is because the deployment does not
exist. If returns a 5XX is a BOSH server problem and we can't do
anything about. So the logical return should be an empty deployment, and
let each client of the API decide if that is a problem or not.
> fix: Return empty BoshDeployment when 4XX or 5XX

- README.md
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/AdminController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/ServiceInstanceCleanup.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/provisioning/DummySystemBackupServiceProvider.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/provisioning/ProvisioningPersistenceServiceTest.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/provisioning/ServiceInstanceCleanupSpec.groovy
- broker/src/integration-test/resources/application-test.yml
When a service instance is being purged
an attempt should be made to deregister
the service instance from the backup
system.
> feat: Deregister Backup

- broker/core/database/src/main/groovy/com/swisscom/cloud/sb/broker/repository/PlanRepository.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/ServiceInstanceCleanup.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/BaseSpecification.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/async/job/JobManagerSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/backup/SystemBackupProviderTest.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/provisioning/ProvisioningPersistenceServiceTest.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/provisioning/ServiceInstanceCleanupSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/provisioning/lastoperation/LastOperationJobContextServiceSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/servicedefinition/ServiceDefinitionInitializerSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/mongodb/enterprise/MongoDbEnterpriseFreePortFinderSpec.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/services/statemachine/StateMachineBasedServiceProviderTest.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/util/DBTestUtil.groovy
- broker/src/integration-test/resources/application-test.yml
Service is under certain circumstances not
loaded due to the Lazy loading.
Improve testing time for integrationTests
> bug: Load Service eagerly for Plan

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/util/test/DummyServiceProvider.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/AsyncServiceFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/BindingParametersFunctionalSpec.groovy
- broker/src/functional-test/resources/application-test.yml
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/util/ServiceLifeCycler.groovy
With the latest feature merge, the functional
tests have credhub as credential store enabled.
The functional tests have to be adopted for that.
Furthermore the functional tests take 20 minutes,
with these changes this should be reduced.
> test: Fix functional tests

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/ServiceInstanceCleanup.groovy
- broker/src/integration-test/groovy/com/swisscom/cloud/sb/broker/provisioning/ServiceInstanceCleanupSpec.groovy
A service instance for which a user driven backup was
created does not get deregistered during deprovision. With
this change the deregister of user driven backup artifacts
takes place during the cleanup.
> bug: Deregister Service Instance From Backup During Cleanup

- model/src/main/groovy/com/swisscom/cloud/sb/broker/util/LoggingRequestInterceptor.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/util/RestTemplateBuilder.groovy
This code add additional debug logging to all resttemplate calls.
This enables us to log request and response headers and bodies for
debugging purposes.
> feat: Add Debug Logs for Rest Template

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/BackupStatusConverter.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/RestoreStatusConverter.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/converter/BackupDtoConverter.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/backup/converter/RestoreDtoConverter.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/ServiceInstanceBindingDtoConverter.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/cfapi/converter/ServiceInstanceDtoConverter.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BackupController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BaseController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/BindingController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/CFExtensionsController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/CatalogController.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/ControllerHelper.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/controller/ProvisioningController.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/controller/ProvisioningControllerSpec.groovy
- model/src/main/groovy/com/swisscom/cloud/sb/broker/error/ErrorCode.groovy
Handle Service Instance not retrievable individually
so that proper response code 403 can be returned. Using
403 Forbidden, as the request is understood and technically
correct but not supported for this service.
> bug: Service Instance Not Retrievable

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/provisioning/job/ServiceUpdateJob.groovy
Using Spring Autowire in conjunction
with Quartz does not work with constructor
injection.
> refactor: Use Field Injection

- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/statemachine/BoshStateMachineFactory.groovy
- broker/core/src/main/groovy/com/swisscom/cloud/sb/broker/services/bosh/statemachine/BoshUpdateState.groovy
- broker/core/src/test/groovy/com/swisscom/cloud/sb/broker/services/bosh/statemachine/BoshUpdateStateSpec.groovy
Allow to update a bosh deployment by deploying with an update request.
> feature: Update Bosh Update Flow

- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/AdminControllerSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/BaseFunctionalSpec.groovy
- broker/src/functional-test/groovy/com/swisscom/cloud/sb/broker/functional/ServiceContextFunctionalSpec.groovy
- client/src/main/groovy/com/swisscom/cloud/sb/client/ServiceBrokerClient.groovy
> bug: Fix Failing Functional Tests
